@startuml
'https://plantuml.com/sequence-diagram

class Computadora {
-tipo: Sting
-ram: int
-discoRigido: int
-{static} contador: int
}
ComputadoraFactory -l-> Computadora
class ComputadoraFactory {
- poolComputadoras: HashMap
+ obtenerComputadora(tipo): Computadora
}
@enduml